---
version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: Update & Install Packages
          command: |
            apt-get -y update && apt-get -y install wget
      - checkout
      - run:
          name: Download & Install Binary
          command: |
            wget https://jenkins.pmmp.io/job/PHP-7.2-Linux-x86_64/lastSuccessfulBuild/artifact/PHP_Linux-x86_64.tar.gz
            tar -xvf PHP_Linux-x86_64.tar.gz
      - run:
          name: Lint Source
          command: |
            ./tests/lint.sh -p bin/php7/bin/php -d ./src/jacknoordhuis/chatchannels
      - run:
          name: Build Plugin Phar
          command: |
            bin/php7/bin/php ./build.php
      - store_artifacts:
          path: ChatChannels.phar
          destination: ChatChannels.phar
...